### PR TITLE
feature-basic-java-app

### LINKED ISSUE #8: 3 - Create basic Java app in GitHub
A a developer I need to have basic Java app in order to test out the pipeline 

This will include two folders

- main
- test

Acceptance Criteria 
Basic app added to the repo with folder structure

### LINKED ISSUE #9: 5 - Create Junit tests in the Java App for pipeline execution
As a developer I need to be able to create Junit Tests on that will execute on the pipeline

### PR DESCRIPTION
**Pull request by sharonO13**
Basic calculator App with unit tests

### CODE REVIEW

**Review by JoseSunoj — CHANGES_REQUESTED** [review]
Hi Saharon, you did well. However, a have a few suggestions for the folder structure.
1. we need only src and pom.xml
2. if those folder/file are part of the root folder, then the action workflow will succeed. I confirmed  it and posted it in slack.
3. if you agree the above, then no need to refractor anything.
Thank you.

**Comment by sharonO13** [comment]
> Hi Saharon, you did well. However, I have a few suggestions for the folder structure.
> 
> 1. we need only src and pom.xml
> 2. if those folder/file are part of the root folder, then the action workflow will succeed. I confirmed  it and posted it in slack.
> 3. if you agree the above, then no need to refractor anything.
>    Thank you.

Updates made to folder structure

**Review by JoseSunoj — COMMENTED** [review]
Viewed, changes requested. Approved changes. Tested the app locally after changes. App functions as expected.

**Review by JoseSunoj — COMMENTED** [review]
The app functions as expected.

**Pull request merged**
